max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
fn_args_density = "Compressed"
brace_style = "AlwaysNextLine"
format_strings = true
normalize_comments = true
