max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
fn_args_density = "Compressed"

# The following item is for 0.3+ only
brace_style = "AlwaysNextLine"

# The following 2 items are for 0.2.15 only
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"

format_strings = true
normalize_comments = true
